---
applications:
- name: get-help-with-remote-education-rails-dev
  disk_quota: 1G
  memory: 1G
  instances: 1
  env:
    RAILS_ENV: production
    RACK_ENV: production
    RAILS_SERVE_STATIC_FILES: true
  docker:
    image: dfedigital/get-help-with-remote-education-dev:latest
  services:
  - logit-ssl-drain
  - get-help-with-remote-education-pg-dev