---
applications:
- name: get-help-with-remote-education-proof-of-concept
  disk_quota: 1G
  memory: 1G
  instances: 1
  env:
    RAILS_ENV: production
    RACK_ENV: production
    RAILS_SERVE_STATIC_FILES: true
  docker:
    image: dfedigital/get-help-with-remote-education-dev:poc