name: Deploy rails to staging

# Workflow will run on manual trigger in github actions UI
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-push-container:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=image_commit_tag::ghcr.io/dfe-digital/get-help-with-remote-education-staging:$(git rev-parse --short HEAD)"
          echo "::set-output name=image_latest_tag::ghcr.io/dfe-digital/get-help-with-remote-education-staging:latest"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ghre-docker
          password: ${{ secrets.GH_USER_GHRE_DOCKER_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./ghre-rails
          push: true
          tags: ${{ steps.vars.outputs.image_commit_tag }}, ${{ steps.vars.outputs.image_latest_tag }}

  deploy-to-paas:
    defaults:
      run:
        working-directory: ghre-rails
    runs-on: ubuntu-latest
    needs: build-and-push-container
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=image_commit_tag::ghcr.io/dfe-digital/get-help-with-remote-education-staging:$(git rev-parse --short HEAD)"
      - name: Install CloudFoundry CLI
        shell: bash
        id: install-cf-cli
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf7-cli
      - name: Deploy to Gov.uk PaaS
        id: deploy-to-paas
        shell: bash
        env:
          GH_IMAGE_COMMIT_TAG: ${{ steps.vars.outputs.image_commit_tag }}
        run: |
          cf api https://api.london.cloud.service.gov.uk
          cf auth "${{ secrets.CF_USER_STAGING }}" "${{ secrets.CF_PASSWORD_STAGING }}"
          cf target -o dfe -s get-help-with-remote-education-staging
          cf push -f ./config/manifests/staging_manifest.yml --docker-image $GH_IMAGE_COMMIT_TAG
