name: Deploy to Dev

# Workflow will run on push to main branch
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-to-paas-dev:
    defaults:
      run:
        working-directory: ghre-static
        
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Install CloudFoundry CLI
        shell: bash
        id: install-cf-cli
        run: |
          curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" | tar -zx
          sudo mv cf /usr/local/bin

      - name: install dependencies
        run: |
          npm install
          bundle install

      - name: add basic auth
        run: |
          echo "${{ secrets.BASIC_AUTH_USER }}":"${{ secrets.BASIC_AUTH_HASHED_PASSWORD }}" > source/Staticfile.auth
      
      - name: Use Terraform 0.14.2
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.2

      - name: Terraform init, plan & apply
        id: terraform_deploy
        run: |
          terraform init -reconfigure -upgrade=true -backend-config=bucket="${{ secrets.PRIVATE_S3_BUCKET_DEV }}"
          terraform plan -var-file workspace-variables/dev.tfvars
          terraform apply -auto-approve -var-file workspace-variables/dev.tfvars
        working-directory: terraform
        env:
          TF_VAR_monitoring_username="${{ secrets.MONITORING_USER }}"
          TF_VAR_monitoring_password="${{ secrets.MONITORING_PASSWORD }}"
          TF_VAR_grafana_admin_password="${{ secrets.GRAFANA_ADMIN_PASSWORD_DEV }}"
          TF_VAR_statuscake_username="${{ secrets.STATUSCAKE_USERNAME }}"
          TF_VAR_statuscake_apikey="${{ secrets.STATUSCAKE_APIKEY }}"
          TF_VAR_paas_username="${{ secrets.CF_USER_DEV }}"
          TF_VAR_paas_password="${{ secrets.CF_PASSWORD_DEV }}"

      - name: run tests
        run: |
          bundle exec rspec

      - name: build
        run: |
          bundle exec middleman build

      - name: deploy to gov.uk paas
        id: deploy-to-paas
        shell: bash
        run: |
          cf api https://api.london.cloud.service.gov.uk
          cf auth "${{ secrets.CF_USER_DEV }}" "${{ secrets.CF_PASSWORD_DEV }}"
          cf target -o dfe-teacher-services -s get-help-with-remote-education-dev
          cf target
          cf push -b staticfile_buildpack -p build get-help-with-remote-education-dev
