name: Deploy rails to dev

# Workflow will run on push to main branch
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-push-container:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(git rev-parse --abbrev-ref HEAD)"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          build_args: GIT_COMMIT_SHA=${{ steps.vars.outputs.sha_short }},GIT_BRANCH=${{ steps.vars.outputs.branch }}
          path: ./ghre-rails
          dockerfile: ./ghre-rails/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dfedigital/get-help-with-remote-education-dev
          tags: latest

  deploy-to-paas:
    defaults:
      run:
        working-directory: ghre-rails
    runs-on: ubuntu-latest
    needs: build-and-push-container
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install CloudFoundry CLI
        shell: bash
        id: install-cf-cli
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf7-cli
      - name: Deploy to Gov.uk PaaS
        id: deploy-to-paas
        shell: bash
        env:
          CF_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          CF_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          cf api https://api.london.cloud.service.gov.uk
          cf auth "${{ secrets.CF_USER_DEV }}" "${{ secrets.CF_PASSWORD_DEV }}"
          cf target -o dfe-teacher-services -s get-help-with-remote-education-dev
          cf push get-help-with-remote-education-rails-dev --docker-image dfedigital/get-help-with-remote-education-dev:latest
